name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Node Modules
        run: yarn install
        working-directory: ./ui
      - name: Build Application
        run: yarn run build
        working-directory: ./ui
      - uses: vimtor/action-zip@v1
        with:
          files: fxmanifest.lua LICENSE.md README.md locale.lua version ui/dist client server config.lua languages
          recursive: false
          dest: bcc-vue-boilerplate.zip
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ui
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package-version.outputs.current-version}}"
          prerelease: false
          title: "Release ${{ steps.package-version.outputs.current-version}}"
          files: |
            bcc-vue-boilerplate.zip
